apiVersion: rrsd.zetaapps.in/v1alpha1
kind: Configuration
metadata:
  name: lsg.aether.configuration.product.prdin001011.nova.product
spec:
  metadata:
    id: aether.configuration.product.prdin001011.nova.product
    name: Ezz x ZPay Nova Product
    description: Ezz x ZPay Nova Secured Credit Card Product
    tenantId: "600309"
    tenantCode: lsg
  config:
    format: YAML
    schemaUrl: https://card-program-files.s3.amazonaws.com/schema/product_bundle.yaml
    key: key
    isEncrypted: false
    useVault: false
    value:
      name: Ezz x ZPay Nova
      code: PRDIN001011
      codeSuffix: "1011"
      description: Ezz x ZPay Nova Secured Credit Card Product
      imageUrl: https://assets.ezzbank.in/card-images/nova-card-light-purple.png
      status: active
      bundleCode: BUNIN-NOVA-1011
      source:
        clonedFrom: Template
        clonedProduct: PRDIN001011
