apiVersion: rrsd.zetaapps.in/v1alpha1
kind: Clock
metadata:
  name: bkezz.aura.clock.clkin007002
  namespace: elenchos
spec:
  calendarCode: CALINBKEZZ001
  cbuDuration: 1
  cbusInAdvance: 10
  code: CLKINBKEZZ007002
  metadata:
    description: Book Clock for Chart of Limit
    id: aura.clock.clkin007002
    name: Book Clock for Chart of Limit
    requester:
      module: aura
      moduleVersion: 0.0.1
    tenantCode: bkezz
    tenantId: "700001"
  name: Bank Ezz India Book Clock for Chart of Limit
  clockStartTimeDate: "2026-01-21"
  clockStartTimeHours: 0
  status: ENABLED
  type: BOOK
