kind: Clock
apiVersion: rrsd.zetaapps.in/v1alpha1
metadata:
  name: bkezz.aura.clock.module.8001
  labels:
    rrsd.zetaapps.in/day: day-zero
  annotations:
    zeta.tech/resource-tags: '{"gitDbRepo":"tenant_configuration.aws-default-pp-mumbai.bkezz","gitDbPath":"https://gitea.internal.mum1-pp.zetaapps.in/zetaengg/tenant_configuration.aws-default-pp-mumbai.bkezz.git","filePath":"module_configurations/module_aura/clocks/clock_8001.yaml","tenantCode":"bkezz"}'
  namespace: aura
spec:
  metadata:
    id: aura.clock.module.8001
    name: aura.clock.module.8001
    description: aura.clock.module.8001
    tenantId: "700001"
    tenantCode: bkezz
  calendarCode: CALINBKEZZ001
  cbuDuration: 1
  cbusInAdvance: 10
  code: CLKINBKEZZ8001
  name: Bank Ezz India Weekly Clock CLKINBKEZZ8001
  clockStartTimeDate: "2025-01-01"
  clockStartTimeHours: 0
  status: ENABLED
  type: BOOK
