apiVersion: rrsd.zetaapps.in/v1alpha1
kind: Configuration
metadata:
  name: lsg.emerald.configuration.product.prdin.nova.1011.account-product
spec:
  metadata:
    id: emerald.configuration.product.prdin.nova.1011.account-product
    name: Nova test Credit Card Loan Monthly Product NOVA-1011
    description: Nova test Credit Card Loan Monthly Product NOVA-1011
    tenantId: '600309'
    tenantCode: lsg
  config:
    format: YAML
    schemaUrl: https://banking-assets.s3.ap-south-1.amazonaws.com/hedwig/product_configuration_schema/provider_ruby/account_product_family/account_product/v1/product.yaml
    key: key
    isEncrypted: false
    useVault: false
    value:
      name: Nova test Credit Card Loan Monthly Product NOVA-1011
      code: EAPUS-NOVA-101101
      coaCode: COAUS-NOVA-1011
      accountProductFamilyCode: EPFUS-NOVA-1011
      description: Nova test Credit Card Loan Monthly Product NOVA-1011
      productType: NOVA_CARD_EMI
      productPreferences:
        defaultTenure:
          days: 0
          months: 0
          years: 0
        issuanceEndDate: '2999-12-31'
        issuanceStartDate: '2026-03-01'
        maxLoanAmount:
          amount: 100000000
          currency: INR
        maxTenure:
          days: 0
          months: 60
          years: 0
        minLoanAmount:
          amount: 50000
          currency: INR
        minTenure:
          days: 1
          months: 0
          years: 0
      policies:
        interestPolicy:
          code: EIPUS-NOVA-1011
          version: 1
        repaymentPolicy:
          code: ERPUS-NOVA-1011
          version: 1
        accountClosurePolicy:
          code: ECPUS-NOVA-1011
          version: 1
        accountNumberGenerationPolicy:
          code: ENGUS-NOVA-1011
          version: 1
        amortizationPolicy:
          code: EAPUS-NOVA-1011
          version: 2
        loanLifeCyclePolicy:
          code: ELLCUS-NOVA-1011
          version: 1
        creditAllocationPolicy:
          code: ECAPUS-NOVA-1011
          version: 1
      templateCode: in-credit
