apiVersion: rrsd.zetaapps.in/v1alpha1
kind: Configuration
metadata:
  name: lsg.emerald.configuration.product.prdin.supernova.1012.smartemi.account-product
spec:
  metadata:
    id: emerald.configuration.product.prdin.supernova.1012.smartemi.account-product
    name: Loan Smart EMI Product SUPERNOVA-1012
    description: Loan Smart EMI Product SUPERNOVA-1012
    tenantId: '600309'
    tenantCode: lsg
  config:
    format: YAML
    schemaUrl: https://banking-assets.s3.ap-south-1.amazonaws.com/hedwig/product_configuration_schema/provider_ruby/account_product_family/account_product/v1/product.yaml
    key: key
    isEncrypted: false
    useVault: false
    value:
      name: Loan Smart EMI Product SUPERNOVA-1012
      code: EAPUS-SUPERNOVA-101201
      coaCode: COAUS-SUPERNOVA-1012
      accountProductFamilyCode: EPFUS-SUPERNOVA-1012
      description: Loan Smart EMI Product SUPERNOVA-1012
      productType: POST_PURCHASE_EMI
      productPreferences:
        defaultTenure:
          days: 0
          months: 0
          years: 0
        issuanceEndDate: '2999-12-31'
        issuanceStartDate: '2026-03-01'
        maxLoanAmount:
          amount: 100000000
          currency: INR
        maxTenure:
          days: 0
          months: 60
          years: 0
        minLoanAmount:
          amount: 10000
          currency: INR
        minTenure:
          days: 1
          months: 0
          years: 0
      policies:
        interestPolicy:
          code: EIPUS-SUPERNOVA-1012
          version: 1
        repaymentPolicy:
          code: ERPUS-SUPERNOVA-1012
          version: 1
        accountClosurePolicy:
          code: ECPUS-SUPERNOVA-1012
          version: 1
        accountNumberGenerationPolicy:
          code: ENGUS-SUPERNOVA-1012
          version: 1
        amortizationPolicy:
          code: EAPUS-SUPERNOVA-1012
          version: 2
        loanLifeCyclePolicy:
          code: ELLCUS-SUPERNOVA-1012
          version: 1
        creditAllocationPolicy:
          code: ECAPUS-SUPERNOVA-1012
          version: 1
      templateCode: in-credit
