apiVersion: rrsd.zetaapps.in/v1alpha1
kind: EmeraldLoanLifeCyclePolicy
metadata:
  name: lsg.emerald.emeraldloanlifecyclepolicy.supernova.1012
spec:
  metadata:
    id: emerald.emeraldloanlifecyclepolicy.supernova.1012
    name: Emerald Loan Life Cycle Policy
    description: Emerald Loan Life Cycle Policy
    requester:
      module: emerald-module-e2e
      moduleVersion: 0.0.1
    tenantId: '600309'
    tenantCode: lsg
  validFrom: '2010-04-01T00:00:00.000+05:30'
  validTill: '2099-12-31T00:00:00.000+05:30'
  name: Loan Life Cycle Policy
  description: Loan Life Cycle Policy
  code: ELLCUS-SUPERNOVA-1012
  kfsTemplateCode: https://hercules-assets.mum1-pp.zetaapps.in/statement-templates/3.3.1/sigma/key_fact_statement.html
  loanProposalKFSExpiryInMs: 1000000
  graceDays: 0
  sourceProcessingControls:
    skipInstallmentBilling: false
    skipRepayment: false
  templateCode: us-credit
