kind: Configuration
apiVersion: rrsd.zetaapps.in/v1alpha1
metadata:
  name: lsg.athena.configuration.product.prdus005001.default.resource-product
spec:
  metadata:
    id: athena.configuration.product.prdus005001.default.resource-product
    name: default Resource Product for cardworksuat
    description: default Resource Product for cardworksuat
    tenantId: '600309'
    tenantCode: lsg
  config:
    format: YAML
    schemaUrl: http://localhost
    schemaInlineContent: |
      {"properties":{"code":{"type":"string"},"description":{"type":"string"},"formFactorProducts":{"items":{"type":"string"},"type":"array"},"name":{"type":"string"},"status":{"enum":["ACTIVE","INACTIVE"]},"tags":{"items":{"type":"string"},"type":"array"}},"required":["code","name","description","status"],"type":"object"}
    key: key
    isEncrypted: false
    useVault: false
    value:
      code: RSPUS005001_CARDWORKSUAT
      description: Resource Product cardworksuat
      formFactorProducts:
        - FFPUS005001_CARDWORKSUAT
        - FFPUS00500103_CARDWORKSUAT
        - FFPUS00500102_CARDWORKSUAT
      name: Resource Product cardworksuat
      status: ACTIVE
  viewConfig:
    angelosSchema:
      view:
        entityId: angelos.athena.resource-product
    displayName: default Resource Product for cardworksuat
