kind: Configuration
apiVersion: rrsd.zetaapps.in/v1alpha1
metadata:
  name: bkezz.athena.configuration.product.prdin001001.default.resource-product
spec:
  metadata:
    id: athena.configuration.product.prdin001001.default.resource-product
    name: default Resource Product for Bank Ezz India
    description: default Resource Product for Bank Ezz × ZPay India RuPay credit cards (Nova & Super Nova)
    tenantId: '600309'
    tenantCode: lsg
  config:
    format: YAML
    schemaUrl: http://localhost
    schemaInlineContent: |
      {
        "type": "object",
        "properties": {
          "code": { "type": "string" },
          "description": { "type": "string" },
          "formFactorProducts": {
            "type": "array",
            "items": { "type": "string" }
          },
          "name": { "type": "string" },
          "status": {
            "type": "string",
            "enum": ["ACTIVE","INACTIVE"]
          },
          "tags": {
            "type": "array",
            "items": { "type": "string" }
          }
        },
        "required": ["code","name","description","status"]
      }
    key: key
    isEncrypted: false
    useVault: false
    value:
      code: RPIN001001
      description: Resource Product for Bank Ezz × ZPay India RuPay credit cards
      formFactorProducts:
        - FFPIN001001          
      name: Resource Product - Bank Ezz India RuPay Credit Cards
      status: ACTIVE
      tags:
        - network:RUPAY
        - product:NOVA
        - product:SUPER_NOVA
  viewConfig:
    angelosSchema:
      view:
        entityId: angelos.athena.resource-product
    displayName: default Resource Product for Bank Ezz India RuPay Credit Cards