apiVersion: rrsd.zetaapps.in/v1alpha1
kind: RubyAnnualFeePolicy
metadata:
  name: lsg.ruby.rubyannualfeeepolicy.5001
spec:
  metadata:
    id: ruby.rubyannualfeeepolicy.5001
    name: 5001 Ruby Annual Fee Policy
    description: 5001 Ruby Annual Fee Policy
    requester:
      module: ruby-module-e2e
      moduleVersion: 0.0.1
    tenantId: '600309'
    tenantCode: lsg
  name: Ruby Annual Fee Policy
  code: ANFUS005001
  description: Ruby Annual Fee Policy
  modelParameters:
    fixedAmount:
      baseFee:
        amount: 3000
        currency: USD
  validFrom: '2000-01-01T00:00:00.000-05:00'
  validTill: '2999-01-01T00:00:00.000-05:00'
  templateCode: us-credit
