apiVersion: rrsd.zetaapps.in/v1alpha1
kind: RubyAnnualFeePolicy
metadata:
  name: lsg.ruby.rubyannualfeeepolicy.5001
spec:
  metadata:
    id: ruby.rubyannualfeeepolicy.5001
    name: Supernova 5001 Ruby Annual Fee Policy
    description: Supernova 5001 Ruby Annual Fee Policy
    requester:
      module: ruby-module-e2e
      moduleVersion: 0.0.1
    tenantId: '600309'
    tenantCode: lsg
  name: Supernova Ruby Annual Fee Policy
  code: ANFUS005001
  description: Ruby Annual Fee Policy
  modelParameters:
    fixedAmount:
      baseFee:
        amount: 99900
        currency: INR
  chargeStrategy: DIRECT-APPLY
  chargeStrategyConfig:
    application:
      applicabilityOnwards: keyDateSpecification://code/FIRST_ANNIVERSARY_OF_ACCOUNT_OPEN_DATE
      applyOn: keyDateSpecification://code/BILLING_DATE
      offsetDaysForValueDate: '0'
  remarks: Annual Fee (billed monthly)
  validFrom: '2026-01-01T00:00:00.000+05:30'
  validTill: '2999-01-01T23:09:01.795+07:00'
  templateCode: in-credit
