apiVersion: rrsd.zetaapps.in/v1alpha1
kind: RubyCardReplacementFeePolicy
metadata:
  name: lsg.ruby.rubycardreplacementfeepolicy.5001
spec:
  metadata:
    id: ruby.rubycardreplacementfeepolicy.5001
    name: 5001 Ruby Card Replacement Fee Policy
    description: 5001 Ruby Card Replacement Fee Policy
    requester:
      module: ruby-module-e2e
      moduleVersion: 0.0.1
    tenantId: '600309'
    tenantCode: lsg
  name: Ruby Card Replacement Fee Policy
  code: CRFUS005001
  description: Ruby Card Replacement Fee Policy
  modelParameters:
    fixedAmount:
      baseFee:
        amount: 25000
        currency: INR
    replacementCardIdentifier:
      - key: cardSkuID
        value:
          - SKUIN005001_CARDWORKSUAT
  validFrom: '2026-01-01T00:00:00.000+05:30'
  validTill: '2999-01-01T00:00:00.000-05:00'
  templateCode: in-credit
