apiVersion: rrsd.zetaapps.in/v1alpha1
kind: RubyDelinquencyPolicy
metadata:
  name: lsg.ruby.rubydelinquencypolicy.5001
spec:
  metadata:
    id: ruby.rubydelinquencypolicy.5001
    name: 5001 Delinquency Policy
    description: 5001 Delinquency Policy
    requester:
      module: ruby-module-e2e
      moduleVersion: 0.0.1
    tenantId: '600309'
    tenantCode: lsg
  name: Delinquency Policy
  code: DLQIN005001
  description: Delinquency Policy
  delinquencyRules:
    - level: 1
      description: One Payment past due
      fromDays: 1
      toDays: 30
    - level: 2
      description: 2 payments past Due
      fromDays: 31
      toDays: 60
    - level: 3
      description: 3 payments past due
      fromDays: 61
      toDays: 90
    - level: 4
      description: 4 payments past due
      fromDays: 91
      toDays: 120
    - level: 5
      description: 5 payments past due
      fromDays: 121
      toDays: 150
    - level: 6
      description: 6 payments past due
      fromDays: 151
      toDays: 180
  paymentVariance:
    amount: 10000
    currency: INR
  paymentVarianceForLateFee:
    amount: 5000
    currency: INR
  delinquencyAgeingBasis: dueDate
  balanceLevelForDueReview: CURRENTBALANCE
  dpdAgeingBasis: dueDate
  validFrom: '2025-01-01T00:00:00.000+05:30'
  validTill: '9918-01-01T00:00:00.000-05:00'
  templateCode: in-credit
