apiVersion: rrsd.zetaapps.in/v1alpha1
kind: RubyDormancyPolicy
metadata:
  name: lsg.ruby.rubydormancypolicy.5001
spec:
  metadata:
    id: ruby.rubydormancypolicy.5001
    name: 5001 Dormancy Policy
    description: 5001 Dormancy Policy
    requester:
      module: ruby-module-e2e
      moduleVersion: 0.0.1
    tenantId: '600309'
    tenantCode: lsg
  name: Dormancy Policy
  code: DORIN005001
  description: Dormancy Policy
  applicableVoucherCodesCredit:
    - CARD_PURCHASE_CLEARANCE_REFUND
    - CARD_CASH_CLEARANCE_REFUND
    - REPAYMENT
  applicableVoucherCodesDebit:
    - CARD_PURCHASE_PLACE_HOLD
    - CARD_CASH_PLACE_HOLD
    - CARD_PURCHASE_CLEARANCE_AGAINST_HOLD
    - CARD_CASH_CLEARANCE_AGAINST_HOLD
  dormancyRules:
    - level: 1
      description: Dormant for 30 days
      days: 30
    - level: 2
      description: Dormant for 120 days
      days: 120
    - level: 3
      description: Dormant for 365 days
      days: 365
  validFrom: '2025-01-01T00:00:00.000+05:30'
  validTill: '2999-01-01T00:00:00.000-05:00'
  templateCode: in-credit
