apiVersion: rrsd.zetaapps.in/v1alpha1
kind: RubyForexMarkupAdvanceFeePolicy
metadata:
  name: lsg.ruby.rubyforexmarkupadvancefeepolicy.5001
spec:
  metadata:
    id: ruby.rubyforexmarkupadvancefeepolicy.5001
    name: 5001 Ruby Forex Markup Advance Fee Policy
    description: 5001 Ruby Forex Markup Advance Fee Policy
    requester:
      module: ruby-module-e2e
      moduleVersion: 0.0.1
    tenantId: '600309'
    tenantCode: lsg
  name: 5001 Ruby Forex Markup Advance Fee Policy
  code: FCCUS005001
  description: 5001 Ruby Forex Markup Advance Fee Policy
  modelParameters:
    variableAmount:
      - domestic: 'true'
        crossCurrency: 'false'
        range:
          min: 0
        percentage: 0
      - domestic: 'true'
        crossCurrency: 'true'
        range:
          min: 100
        percentage: 1
      - domestic: 'false'
        crossCurrency: 'true'
        range:
          min: 100
        percentage: 1
      - domestic: 'false'
        crossCurrency: 'false'
        range:
          min: 0
        percentage: 0
  validFrom: '2000-01-01T00:00:00.000-05:00'
  validTill: '2999-01-01T00:00:00.000-05:00'
  templateCode: us-credit
