apiVersion: rrsd.zetaapps.in/v1alpha1
kind: RubyLoanConversionPreClosureFeePolicy
metadata:
  name: lsg.ruby.loanpreclosurefeepolicy.5001
spec:
  code: LCPUS005001
  description: loan conversion fee policy changed
  metadata:
    description: 5001 loan preclosure fee policy
    id: ruby.loanpreclosurefeepolicy.5001
    name: 5001 loanpreclosure fee policy
    requester:
      module: ruby-module-e2e
      moduleVersion: 0.0.1
    tenantCode: lsg
    tenantId: '600309'
  modelParameters:
    taxes:
      cgst: 9
      igst: 18
      sgst: 9
    preClosureFee: 3
    waiverReasonCode:
      - PRECLOSED_REFUND
      - PRECLOSED_CHARGEOFF
      - PRECLOSED_DELINQUENCY
      - PRECLOSED_BUNDLE_STATUS
    baseStateLocation: TN
    invoiceNumberConfig:
      status: ACTIVE
      ingConfig:
        code: INGUS001002
        version: '1'
      generationContext:
        clockType: BOOK
        dateFormat: yyDDD
        customFields:
          sourceSystemCode: TCC
      generationStrategy: DATE_BASED
  name: loan conversion preclosure fee adjustment  policy
  templateCode: us-credit
  validFrom: '2010-04-01T00:00:00.000+05:30'
  validTill: '2999-12-31T00:00:00.000+05:30'
