apiVersion: rrsd.zetaapps.in/v1alpha1
kind: RubyRepaymentPolicy
metadata:
  name: lsg.ruby.rubyrepaymentpolicy.5001
spec:
  metadata:
    id: ruby.rubyrepaymentpolicy.5001
    name: 5001 Ruby Repayment Policy
    description: 5001 Ruby Repayment Policy
    requester:
      module: ruby-module-e2e
      moduleVersion: 0.0.1
    tenantId: '600309'
    tenantCode: lsg
  name: Ruby Repayment Policy
  code: REPIN005001
  description: Ruby Repayment Policy
  repaymentAllocation:
    aboveMAD:
      allocationModel: HIGHESTTOLOWESTAPR
      allocationTieBreaker: REPAYMENTSEQUENCE
      repaymentSequence:
        - chargeOffStatuses:
            - '*'
          repaymentSequenceTieBreaker: FIFO
          settlementPriority:
            - LateFeeBilled
            - InsufficientFundFeeBilled
            - OverlimitFeeBilled
            - CollectionFeeBilled
            - CashAdvanceFeeBilled
            - RetailMiscFeeBilled
            - RetailServiceFeeBilled
            - AnnualFeeBilled
            - CashInterestBilled
            - EMIInterestBilled
            - RetailInterestBilled
            - CashPrincipalBilled
            - EMIPrincipalBilled
            - RetailPrincipalBilled
            - LateFeeUnbilled
            - InsufficientFundFeeUnbilled
            - OverlimitFeeUnbilled
            - CollectionFeeUnbilled
            - CashAdvanceFeeUnbilled
            - RetailMiscFeeUnbilled
            - RetailServiceFeeUnbilled
            - AnnualFeeUnbilled
            - CashInterestUnbilled
            - EMIInterestUnbilled
            - RetailInterestUnbilled
            - CashPrincipalUnbilled
            - EMIPrincipalUnbilled
            - RetailPrincipalUnbilled
    belowMAD:
      allocationModel: LOWESTTOHIGHESTAPR
      allocationTieBreaker: REPAYMENTSEQUENCE
      repaymentSequence:
        - chargeOffStatuses:
            - '*'
          repaymentSequenceTieBreaker: FIFO
          settlementPriority:
            - LateFeeBilled
            - InsufficientFundFeeBilled
            - OverlimitFeeBilled
            - CollectionFeeBilled
            - CashAdvanceFeeBilled
            - RetailMiscFeeBilled
            - RetailServiceFeeBilled
            - AnnualFeeBilled
            - CashInterestBilled
            - EMIInterestBilled
            - RetailInterestBilled
            - CashPrincipalBilled
            - EMIPrincipalBilled
            - RetailPrincipalBilled
            - LateFeeUnbilled
            - InsufficientFundFeeUnbilled
            - OverlimitFeeUnbilled
            - CollectionFeeUnbilled
            - CashAdvanceFeeUnbilled
            - RetailMiscFeeUnbilled
            - RetailServiceFeeUnbilled
            - AnnualFeeUnbilled
            - CashInterestUnbilled
            - EMIInterestUnbilled
            - RetailInterestUnbilled
            - CashPrincipalUnbilled
            - EMIPrincipalUnbilled
            - RetailPrincipalUnbilled
  otherCreditAllocation:
    allocationModel: HIGHESTTOLOWESTAPR
    allocationTieBreaker: REPAYMENTSEQUENCE
    repaymentSequence:
      - chargeOffStatuses:
          - '*'
        repaymentSequenceTieBreaker: FIFO
        settlementPriority:
          - LateFeeBilled
          - InsufficientFundFeeBilled
          - OverlimitFeeBilled
          - CollectionFeeBilled
          - CashAdvanceFeeBilled
          - RetailMiscFeeBilled
          - RetailServiceFeeBilled
          - AnnualFeeBilled
          - CashInterestBilled
          - EMIInterestBilled
          - RetailInterestBilled
          - CashPrincipalBilled
          - EMIPrincipalBilled
          - RetailPrincipalBilled
          - LateFeeUnbilled
          - InsufficientFundFeeUnbilled
          - OverlimitFeeUnbilled
          - CollectionFeeUnbilled
          - CashAdvanceFeeUnbilled
          - RetailMiscFeeUnbilled
          - RetailServiceFeeUnbilled
          - AnnualFeeUnbilled
          - CashInterestUnbilled
          - EMIInterestUnbilled
          - RetailInterestUnbilled
          - CashPrincipalUnbilled
          - EMIPrincipalUnbilled
          - RetailPrincipalUnbilled
  repaymentReversal:
    excessAttributionPostingCategory: RetailPrincipalUnbilled
    lateFeeAdjustment: true
    interestAdjustment: true
  validFrom: '2025-01-01T00:00:00.000+05:30'
  validTill: '2999-01-01T00:00:00.000-05:00'
  templateCode: in-credit
