apiVersion: rrsd.zetaapps.in/v1alpha1
kind: RubyRepaymentReversalWithFeePolicy
metadata:
  name: lsg.ruby.repaymentreversalwithfeepolicy.6001
spec:
  metadata:
    id: ruby.repaymentreversalwithfeepolicy.6001
    name: 6001 Repayment Reversal with Fee Policy
    description: 6001 Repayment Reversal with Fee Policy
    requester:
      module: ruby-module-e2e
      moduleVersion: 0.0.1
    tenantId: '600309'
    tenantCode: lsg
  name: Repayment Reversal with Fee Policy
  code: RRFIN006001
  description: Repayment Reversal with Fee Policy
  modelParameters:
    assessmentType: REPEATED_OFFENCE
    restrictOnOtherFees:
      - LateFee
    chequeReturnReasonCodes:
      - CHEQUE_RETURN_WITH_FEE
      - INSUFFICIENT_FUNDS
      - ACCOUNT_CLOSED
      - UNABLE_TO_LOCATE_ACCOUNT
      - INVALID_ACCOUNT_NUMBER
      - CUSTOMER_REVOKED_AUTHORIZATION
      - PAYMENT_STOPPED
      - INVALID_ACH_ROUTING_NUMBER
      - BENEFICIARY_OR_ACCOUNT_HOLDER_DECEASED
      - ACCOUNT_FROZEN_OR_RETURNED_PER_OFAC
    repeatedOccurrenceAmount:
      baseAmount: 100000
    firstOccurrenceAmount:
      baseAmount: 75000
    ceilingLimitLevel: MINIMUMPAYMENTDUE
    maxFeeDebitsPerCycle: 1
    repeatOccurrenceWindow:
      type: CYCLES
      count: '6'
    considerReversedInstances: true
  precedenceCode: ZZ0015
  validFrom: '2026-01-01T00:00:00.000+05:30'
  validTill: '9999-01-01T00:00:00.000-07:00'
  templateCode: in-credit
