kind: RubyAddOnFeePolicy
apiVersion: rrsd.zetaapps.in/v1alpha1
metadata:
  name: lsg.ruby.rubyaddonfeepolicy.module.6001
  labels:
    rrsd.zetaapps.in/day: day-zero
  annotations:
    zeta.tech/resource-tags: '{"gitDbRepo":"tenant_configuration.aws-default-pp-mumbai.lsg","gitDbPath":"https://gitea.internal.mum1-pp.zetaapps.in/zetaengg/tenant_configuration.aws-default-pp-mumbai.lsg.git","filePath":"module_configurations/module_ruby/add-on-joining-fee-policies/ruby-add-on-fee-policy_6001.yaml","tenantCode":"lsg"}'
  namespace: ruby
spec:
  metadata:
    id: ruby.rubyaddonfeepolicy.module.6001
    name: ruby.rubyaddonfeepolicy.module.6001
    description: ruby.rubyaddonfeepolicy.module.6001
    requester:
      module: ruby-module-e2e
      moduleVersion: 0.0.1
    tenantId: '600309'
    tenantCode: lsg
  name: Ruby Add-on User Joining Fee Policy
  code: AJFIN006001
  description: Ruby Add-on User Joining Fee Policy
  modelParameters:
    fixedAmount:
      baseFee:
        amount: 49900
        currency: INR
    feeCriteria:
      feeBasisEntity: AH
      feePerEntity: true
      thresholdCount: 1
      includeAllEntities: true
  chargeStrategy: DIRECT-APPLY
  chargeStrategyConfig:
    application:
      applyOn: keyDateSpecification://code/ACCOUNT_OPEN_DATE
      offsetDaysForValueDate: '0'
  validFrom: '2025-01-01T00:00:00.000+05:30'
  validTill: '2998-01-01T00:00:00.000-07:00'
  templateCode: in-credit
