apiVersion: rrsd.zetaapps.in/v1alpha1
kind: RubyStatementPolicy
metadata:
  name: lsg.ruby.rubystatementpolicy.5001
spec:
  metadata:
    id: ruby.rubystatementpolicy.5001
    name: 5001 Ruby Statement Policies
    description: 5001 Ruby Statement Policies
    requester:
      module: ruby-module-e2e
      moduleVersion: 0.0.1
    tenantId: '600309'
    tenantCode: lsg
  validFrom: '2026-01-01T00:00:00.000+05:30'
  validTill: '2999-01-01T00:00:00.000-05:00'
  name: Statement Policy
  description: Statement Policy
  code: STMIN005001
  physicalStatementThreshold: '0'
  dueDays: 2
  graceDays: 1
  payByHolidayTreatment: retainHoliday
  dueDaysCalculationMethod: DueDays
  allowedStatementCycles:
    - billingCycle: CYCIN00500101
    - billingCycle: CYCIN00500102
    - billingCycle: CYCIN00500103
    - billingCycle: CYCIN00500104
    - billingCycle: CYCIN00500105
    - billingCycle: CYCIN00500106
    - billingCycle: CYCIN00500107
    - billingCycle: CYCIN00500109
    - billingCycle: CYCIN00500110
    - billingCycle: CYCIN00500111
    - billingCycle: CYCIN00500112
    - billingCycle: CYCIN00500113
    - billingCycle: CYCIN00500114
    - billingCycle: CYCIN00500115
    - billingCycle: CYCIN00500116
    - billingCycle: CYCIN00500117
    - billingCycle: CYCIN00500118
    - billingCycle: CYCIN00500119
    - billingCycle: CYCIN00500120
    - billingCycle: CYCIN00500121
    - billingCycle: CYCIN00500122
    - billingCycle: CYCIN00500123
    - billingCycle: CYCIN00500124
    - billingCycle: CYCIN00500125
    - billingCycle: CYCIN00500126
    - billingCycle: CYCIN00500127
    - billingCycle: CYCIN00500128
    - billingCycle: CYCIN00500129
  password: function password(context) { return 'password' }
  statementTemplateCode: statement.html
  applyLateFeesOn: GRACE_DATE
  valueDateOfLateFees: GRACE_DATE
  ytdSummaryEnabled: true
  isProbableLateFeeEnabled: true
  isInterestBreakupEnabled: true
  yearlyCycle: CYCIN00500108
  billingCycleChangeConfig:
    coolOffDaysBetweenBillingCycleChange: 0
    rules:
      - maxLimit: 1
        period: YEARLY
  templateCode: in-credit
