apiVersion: rrsd.zetaapps.in/v1alpha1
kind: EmeraldLoanConversionPolicy
metadata:
  name: lsg.emerald.emeraldloanconversionpolicy.5001
spec:
  metadata:
    id: emerald.emeraldloanconversionpolicy.5001
    name: 5001 Emerald Loan Conversion Policy
    description: 5001 Emerald Loan Conversion Policy
    requester:
      module: emerald-module-e2e
      moduleVersion: 0.0.1
    tenantId: '600309'
    tenantCode: lsg
  validFrom: '2026-03-01T00:00:00.000+05:30'
  validTill: '2999-11-31T00:00:00.000+05:30'
  name: Emerald Loan Conversion Policy
  description: Emerald Loan Conversion Policy
  code: ELCUS005001
  accountProvider: ruby
  allowedLoanTypes:
    - autoRefundProcessing: true
      creditEffectiveDateForLoanConversion: loanConversionValueDate
      loanValueDate: LOAN_BOOKING_DATE
      loanName: Merchant EMI loan
      loanProductID: ''
      maxActiveLoansAllowed: 5
      loanType: merchantEMI
      processingFeeReversalOnLoanCancellation: true
      transactionEligibility:
        disAllowedMerchantCategoryCodes:
          - '1409'
          - '2741'
          - '2791'
          - '4214'
          - '4215'
          - '4225'
          - '4468'
          - '4789'
          - '4814'
          - '4821'
          - '4829'
          - '4900'
          - '5047'
          - '5094'
          - '5122'
          - '5172'
          - '5300'
          - '5309'
          - '5411'
          - '5422'
          - '5441'
          - '5451'
          - '5462'
          - '5499'
          - '5521'
          - '5541'
          - '5542'
          - '5592'
          - '5811'
          - '5812'
          - '5813'
          - '5814'
          - '5912'
          - '5921'
          - '5933'
          - '5944'
          - '5960'
          - '5962'
          - '5963'
          - '5966'
          - '5967'
          - '5968'
          - '5969'
          - '5983'
          - '5993'
          - '6010'
          - '6011'
          - '6012'
          - '6050'
          - '6051'
          - '6211'
          - '6513'
          - '6529'
          - '6531'
          - '6533'
          - '6538'
          - '6540'
          - '7273'
          - '7276'
          - '7311'
          - '7322'
          - '7339'
          - '7349'
          - '7361'
          - '7372'
          - '7375'
          - '7392'
          - '7393'
          - '7399'
          - '7512'
          - '7513'
          - '7519'
          - '7631'
          - '7800'
          - '7801'
          - '7802'
          - '7994'
          - '7995'
          - '7997'
          - '8351'
          - '8398'
          - '8641'
          - '8651'
          - '8661'
          - '8675'
          - '8699'
          - '8911'
          - '8931'
          - '8999'
          - '9222'
          - '9223'
          - '9311'
          - '9399'
          - '9402'
          - '9405'
        minTransactionAmount: 50000
        maxNumberOfDaysForTransactionConversion: 7
    - autoRefundProcessing: true
      creditEffectiveDateForLoanConversion: loanConversionValueDate
      loanName: Smart EMI loan
      loanProductID: ''
      loanType: smartEMI
      processingFeeReversalOnLoanCancellation: true
      transactionEligibility:
        disAllowedMerchantCategoryCodes:
          - '1409'
          - '2741'
          - '2791'
          - '4214'
          - '4215'
          - '4225'
          - '4468'
          - '4789'
          - '4814'
          - '4821'
          - '4829'
          - '4900'
          - '5047'
          - '5094'
          - '5122'
          - '5172'
          - '5300'
          - '5309'
          - '5411'
          - '5422'
          - '5441'
          - '5451'
          - '5462'
          - '5499'
          - '5521'
          - '5541'
          - '5542'
          - '5592'
          - '5811'
          - '5812'
          - '5813'
          - '5814'
          - '5912'
          - '5921'
          - '5933'
          - '5944'
          - '5960'
          - '5962'
          - '5963'
          - '5966'
          - '5967'
          - '5968'
          - '5969'
          - '5983'
          - '5993'
          - '6010'
          - '6011'
          - '6012'
          - '6050'
          - '6051'
          - '6211'
          - '6513'
          - '6529'
          - '6531'
          - '6533'
          - '6538'
          - '6540'
          - '7273'
          - '7276'
          - '7311'
          - '7322'
          - '7339'
          - '7349'
          - '7361'
          - '7372'
          - '7375'
          - '7392'
          - '7393'
          - '7399'
          - '7512'
          - '7513'
          - '7519'
          - '7631'
          - '7800'
          - '7801'
          - '7802'
          - '7994'
          - '7995'
          - '7997'
          - '8351'
          - '8398'
          - '8641'
          - '8651'
          - '8661'
          - '8675'
          - '8699'
          - '8911'
          - '8931'
          - '8999'
          - '9222'
          - '9223'
          - '9311'
          - '9399'
          - '9402'
          - '9405'
        minTransactionAmount: 1000
        maxNumberOfDaysForTransactionConversion: 60
  bundleStatusValuesForAutoPreClosure:
    autoBundleStatusValues:
      - Z1
      - Z2
    manualBundleStatusValues:
      - C1
      - C2
      - C3
      - C4
      - D1
      - E1
      - E2
      - E3
      - E4
      - E5
      - E6
      - F1
      - W1
      - X1
  daysPastDueForAutoPreClosure: 145
  installmentBillingDays: 1
  installmentDateRule:
    addOnDays: 1
    mode: BILLING_DATE
  periodForLoanCancellationOnRefund: 0
  templateCode: in-credit
